version: '3'

services:
  app: 
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - "3000:3000"
    env_file: 
      - .env 
    environment:
      DATABASE_URL: "mysql://sweeft:sweeft@mysql:3306/sweeft-database?schema=public"

  mysql:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: sweeft-database
      MYSQL_USER: sweeft
      MYSQL_PASSWORD: sweeft
    volumes:
      - ./mysql_data:/var/lib/mysql
