version: '3'

services:
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: YouDontWannaIt
      MYSQL_USER: sweeftUser
      MYSQL_PASSWORD: sweeftPassword
      MYSQL_DATABASE: sweeft_db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      retries: 20
      interval: 5s
      timeout: 10s

  app: 
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - "3000:3000"
    env_file: 
      - .env 
    depends_on:
      mysql:
        condition: service_healthy