# Start from the Node.js LTS version
FROM node:latest
# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json separately
COPY package.json .
COPY package-lock.json .

RUN npm install 

COPY . .
# Generate Prisma client

RUN npx prisma generate

RUN npm run build
# Expose the port
EXPOSE 3000 
# Start the application in watch mode
CMD ["npm","run" ,"start:prod"]
