# Start from the Node.js LTS version
FROM node:latest
# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json separately
COPY package.json .
COPY package-lock.json .

RUN npm install 

COPY . .
RUN  npx prisma generate
RUN apt-get update && apt-get install -y default-mysql-client
RUN npm run build

EXPOSE 3000 


CMD ["npm","run" ,"start:prod"]